### ISSUE TITLE
Replace Genero language syntax files with official files

### ISSUE THREAD

**Issue by sebflaesch** [github-linguist/linguist#6629] opened 2023-12-07 16:08 UTC
New official syntax language files provided by FourJs are available here:
https://github.com/FourjsGenero/GeneroFgl.tmbundle

We need to replace the existing files created by hand by Bryan Jackson (@alienriver49) in 2020.

Bryan, we discussed this today and I thank you again for your valued contribution.
Please just confirm here that you accept that we replace your original syntax files with ours.

Cheers!
Seb

**Comment by lildude** [comment] 2023-12-07 16:10
Closing as a dupe of https://github.com/github-linguist/linguist/issues/6628

**Comment by lildude** [comment] 2023-12-07 16:11
Oh wait. You mean the grammar files. Re-opening, but not your repo is not accessible.

**Comment by sebflaesch** [comment] 2023-12-07 16:12
@lildude #6629 and #6628 can be provided as different pull requests so please can we keep both open?

**Comment by alienriver49** [comment] 2023-12-07 16:24
I am good with my version of the grammars being replaced with the official grammars maintained by the author(s) of the language. Thank you again @sebflaesch!

**Comment by sebflaesch** [comment] 2023-12-07 16:39
https://github.com/FourjsGenero/GeneroFgl.tmbundle is now public.
We will work on a pull request.

**Comment by sebflaesch** [comment] 2023-12-08 12:47
I think I need some help on this:

The new TextMate files (https://github.com/FourjsGenero/GeneroFgl.tmbundle) we would like to be used by Linguist/Github are defining new language names and identifiers (for the two distinct file types .4gl and .per), that do not match the names and ids that are in place.

Consequently, I guess that a simple "--replace" option with script/add-grammar would not work.

In such case, what is the best practice? Keep in mind that the author of the current definition (@alienriver49) is one of our customers and is ok to replace all of the existing definitions by ours.

In fact, we have two "language" definitions:
1) For .4gl files: "Genero" (that would change to "Genero 4gl")
2) For .per files: "Genero Forms" (that would change to "Genero Forms (per)" or a better name like "Genero per")

It is possible to do a complete drop of the existing definitions, and add again the new languages definitions with the script/add-grammar command? I could not find the instructions to drop a definition, in https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md. 

Regarding samples (issue #6628), my understanding is that the directory names under TOP/samples must match the language names, correct? If yes, we should provide a single pull request for both #6628 and #6629. And we should certainly find a better name for the .per files, because non of the existing language names I can see use ( ) parentheses...

**Comment by sebflaesch** [comment] 2023-12-08 16:01
@lildude:

By ID do you mean the "language_id" field in lib/linguist/languages.yml, that is produced by the script/update-ids?

For now, in my local fork, I could manage to revert the original commit, setup the ruby/docker env and add from scratch the new languages "Genero 4gl" (instead of "Genero") and "Genero per" (instead of "Genero Forms"), with the regular script/add-grammar process, and created new IDs with script/update-ids ...

Would it be an issue, if I reuse the IDs ("language_id") that where generated by the first commit, but using the new names "Genero 4gl" / "Genero per" of my new adding?

This would save me some more additional work!

Seb

**Comment by lildude** [comment] 2023-12-08 16:12
> By ID do you mean the "language_id" field in lib/linguist/languages.yml, that is produced by the script/update-ids?

Yes.

> For now, in my local fork, I could manage to revert the original commit, setup the ruby/docker env and add from scratch the new languages "Genero 4gl" (instead of "Genero") and "Genero per" (instead of "Genero Forms"), with the regular script/add-grammar process, and created new IDs with script/update-ids ...

There's no need to revert the original commit; it's really not necessary. Follow the steps for replacing the grammar, commit those changes, rename the entries as you wish, commit those changes. Several files will be changed but the only changes in the `languages.yml` file will be the two `name` lines. 

I will reject the PR if you change the IDs as I said before: these must not change.

**Comment by sebflaesch** [comment] 2023-12-08 16:19
Ok no worries: I clearly understood that the language IDs must NOT change.
I was wondering if I could just reuse what I have prepared, just by using the existing IDs.
But I will try to use the "replace" method and the renaming as you suggest.

**Comment by lildude** [comment] 2023-12-08 17:49
I gave you the [exact command to run earlier](https://github.com/github-linguist/linguist/issues/6629#issuecomment-1847341684) 😉

This won’t update languages.yml but will take care of everything else.

**Comment by lildude** [comment] 2023-12-08 17:50
Start the PR and we can continue this there as it’s best suited in the PR.

**Comment by sebflaesch** [comment] 2023-12-09 10:24
@lildude : I have worked on changes, **but this is only for validation! please do not apply!**

Would you mind check the changes I have prepared and tell me if something is missing?
Commits are visible in my testing fork:
https://github.com/github-linguist/linguist/compare/master...sebflaesch:linguist-genero:issue-6629

Note that there is NO license file (our TM repo has "The Unlicense") - is this an issue? Should it be an MIT license?

**Comment by lildude** [comment] 2023-12-09 14:10
Diff looks good from a quick glance.

> Note that there is NO license file (our TM repo has "The Unlicense") - is this an issue? Should it be an MIT license?

We need a license file, even for the The Unlicense. The text from https://choosealicense.com/licenses/unlicense/ in a LICENSE file will do the trick.

**Comment by sebflaesch** [comment] 2023-12-10 09:36
Sorry I was not clear: We have that "unlicense" text:
   https://github.com/FourjsGenero/GeneroFgl.tmbundle/blob/master/LICENSE.txt
PR will come after some renaming in
   https://github.com/FourjsGenero/GeneroFgl.tmbundle/tree/master.
Thanks a lot @lildude !

**Comment by sebflaesch** [comment] 2023-12-11 09:35
@lildude : How can I check that my local fork of linguist detects the new "Genero 4gl" and "Genero per" languages replacing the existing languages "Genero" and "Genero Forms"?

When using the github-linguist command, I still see the old languages... What I am missing here?
```
sf@toro (issue-6629):~/genero/devel/github/linguist/linguist-genero$ bin/github-linguist "samples/Genero 4gl/books1.4gl" 
samples/Genero 4gl/books1.4gl: 183 lines (140 sloc)
  type:      Text
  mime type: text/plain
  language:  Genero
  
sf@toro (issue-6629):~/genero/devel/github/linguist/linguist-genero$ bin/github-linguist "samples/Genero per/books1.per" 
samples/Genero per/books1.per: 38 lines (34 sloc)
  type:      Text
  mime type: text/plain
  language:  Genero Forms
```

I have also tried git-linguist command, passing directly file names, but it is not clear to me how to use it, the required OID is not mentioned in the help:
```
sf@toro (issue-6629):~/genero/devel/github/linguist/linguist-genero$ bin/git-linguist breakdown
git-linguist must be called with a specific commit OID to perform language computation
bin/git-linguist:21:in `linguist'
bin/git-linguist:126:in `git_linguist'
bin/git-linguist:147:in `<main>'

sf@toro (issue-6629):~/genero/devel/github/linguist/linguist-genero$ bin/git-linguist breakdown --help
Linguist v7.27.0
Detect language type and determine language breakdown for a given Git repository.

Usage:
git-linguist [OPTIONS] stats|breakdown|dump-cache|clear|disable
    -f, --force                      Force a full rescan
    -c, --commit=COMMIT              Commit to index
```

**Comment by lildude** [comment] 2023-12-11 11:31
@sebflaesch It looks like you've not updated the names in the `languages.yml` file.

**Comment by sebflaesch** [comment] 2023-12-11 11:52
@lildude quite confusing...
Was the script/add-grammar --replace genero.tmbundle ... command not supposed to do that?
Do I have to update the lib/linguist/languages.yml file before/after executing that command?

**Comment by lildude** [comment] 2023-12-11 11:57
> Was the script/add-grammar --replace genero.tmbundle ... command not supposed to do that?

Nope. That script only changes the grammar submodule and related vendor/README.md and cached license files.

That's why I said:

> Follow the steps for replacing the grammar, commit those changes, rename the entries as you wish, commit those changes, rename the samples directories to match the new language names, commit your changes, update the scope lines if the grammars use different scope names, push.

> Do I have to update the lib/linguist/languages.yml file before/after executing that command?

It doesn't matter. It only needs to be done once.

**Comment by sebflaesch** [comment] 2023-12-11 13:08
"Genero 4gl" / "Genero per" does not show up when running:  
```
bundle exec script/cross-validation --test
...
GLSL/recurse1.frag GOOD
GLSL/recurse1.fs GOOD
Genie/Class.gs GOOD
Genie/Hello.gs GOOD
Genie/IDataLoader.gs GOOD
Genie/web.gs BAD (JavaScript)
Gerber Image/LIDARLite.ncl GOOD
Gnuplot/defense_plotter.plt GOOD
...

**Comment by lildude** [comment] 2023-12-11 14:10
Please open a PR. This is all discussion that should be happening in the PR, not the issue. It's also a lot easier to see and also gives us constant confirmation of behaviour via the tests.

**Comment by sebflaesch** [comment] 2023-12-11 14:14
@lildude here is the PR: https://github.com/github-linguist/linguist/pull/6632
Sorry for all the noise, I am new at this and wanted to make sure that the PR is good enough.
Thanks a lot for you help!

**Comment by lildude** [comment] 2023-12-14 07:54
Changes have shipped. Closing.

**Closed by lildude** 2023-12-14 07:54 UTC
Labels: Improvement

**Comment by sebflaesch** [comment] 2023-12-14 08:14
@lildude : Seems that something is not working...
I see "Other" language instead of "Genero 4gl" or "Genero per", in Genero repositories such as:
https://github.com/FourjsGenero/ex_checkbox_tree
Should I open another issue?

**Comment by lildude** [comment] 2023-12-14 10:27
> Should I open another issue?

No need. This is because the language has been renamed but the cache not invalidated. We don't invalidate the cache when making changes via Linguist as this would be incredibly resource intensive given the number of repositories involved. Pushing a new change will force a re-analysis and things should reflect the new name.

You can see the result of this in my [fork](https://github.com/lildude/ex_checkbox_tree) (I'll delete this later) in which I edited the README to force a reanalysis:

![New languages](https://github.com/github-linguist/linguist/assets/627280/329da7be-89fa-439f-93f7-9d96f7b69717)

**Comment by sebflaesch** [comment] 2023-12-14 10:34
ok got it! thanks a lot!

**Comment by sebflaesch** [comment] 2023-12-14 10:36
Any trick to force a Linguist re-analysis of sources without pushing changes into a given repo?

**Comment by lildude** [comment] 2023-12-14 13:12
> Any trick to force a Linguist re-analysis of sources without pushing changes into a given repo?

Nope. This is by design as per the same reasoning for not invalidating the caches.
