### ISSUE TITLE
Add Unison language

### ISSUE THREAD

**Issue by MichaelHinrichs** [github-linguist/linguist#6945] opened 2024-07-19 18:34 UTC
## Language name
Unison

## URL of example repository
https://github.com/unisonweb/unison/tree/trunk/unison-src

## URL of syntax highlighting grammar
https://github.com/unisonweb/unison/tree/trunk/unison-syntax

## Most popular extensions
.u (May cause false positives with Unreal Engine repos.)
.uu
.cable

## Detected language

**Comment by lildude** [comment] 2024-09-25 08:00
Dupe of https://github.com/github-linguist/linguist/issues/6909

**Closed by lildude** 2024-09-25 08:00 UTC
Labels: Add Language, Good First Issue
