### ISSUE TITLE
Add Language: Luau

### ISSUE THREAD

**Issue by daws-sysadmin** [github-linguist/linguist#6763] opened 2024-03-18 14:06 UTC
Luau is a programming language used on the incredibly platform Roblox, which has recently become it's own independent project.

[Luau repository](https://github.com/luau-lang/luau)

Syntax is practically the same as Lua.
https://luau-lang.org/syntax

## Most popular extensions

.luau

## Detected language
Plain text

**Comment by lildude** [comment] 2024-03-18 14:33
Closing as a duplicate of https://github.com/github-linguist/linguist/issues/6000

**Closed by lildude** 2024-03-18 14:33 UTC
Labels: Add Language, Good First Issue

**Comment by daws-sysadmin** [comment] 2024-03-18 14:38
my bad, thx
