### ISSUE TITLE
CMake Multiline Comments

### ISSUE THREAD

**Issue by RamtinKosari** [github-linguist/linguist#6496] opened 2023-07-30 07:56 UTC
## Describe the bug
Linguist Doesnt Support Multiline Commenting that is Avalible from CMake Version 3,

### Expected behaviour
cmake multiline format is like :

```cmake
  #[[
  cmake_minimum_required(VERSION 3.20.2)
  
  project(myproject)
  ]]
```

using #[[ for init and ]] for close

### Related discussion

 Received It from Discussions, link :
https://github.com/orgs/community/discussions/60701

### Additional notes

thank you

**Comment by lildude** [comment] 2023-07-31 06:24
> Linguist Doesnt Support Multiline Commenting that is Avalible from CMake Version 3,

Correct because Linguist doesn't support any syntax highlighting… it only collects the grammar for use by GitHub's highlighting engines. 😉

As detailed in the [troubleshooting doc](https://github.com/github-linguist/linguist/blob/master/docs/troubleshooting.md#theres-a-problem-with-the-syntax-highlighting-of-a-file), all syntax highlighting issues should be raised with the respective grammar maintainers:

> ## There's a problem with the syntax highlighting of a file
> 
> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules [as listed here](/vendor/README.md).
> 
> If you experience an issue with the syntax-highlighting on GitHub, **please report the issue to the upstream grammar repository, not here.**
> Grammars are updated every time we build the Linguist gem so upstream bug fixes are automatically incorporated as they are fixed.

Closing as this is not a bug in Linguist.

**Closed by lildude** 2023-07-31 06:24 UTC
Labels: Bug

**Comment by jamesETsmith** [comment] 2023-08-07 15:51
It appears this issue has already been reported (5 years ago) https://github.com/textmate/cmake.tmbundle/issues/6

**Comment by nilason** [comment] 2024-05-13 17:22
As I noted in https://github.com/github-linguist/linguist/issues/6659#issuecomment-2104322331 there is a fix available to this upstream, but due lack of activity it may be better (for the time being) to link to my fork.
